# OSEMN Exercises

In [3]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [11]:
l = np.random.randint(0,10,10)
l = list(l)
with open('C:/Users/Utente/Desktop/test/simple_data.txt', 'w') as f:
    for elem in l:
        f.write(str(elem) + '\t')

2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [13]:
m = np.random.randint(0,10,25)
m = m.reshape(5,5)
print(m)
with open('C:/Users/Utente/Desktop/test/data.txt', 'w') as f:
    for i in range(5):
        for j in range(5):
            f.write(str(m[i][j]) + '\t')
        f.write('\n')

[[9 1 4 0 0]
 [6 4 1 2 0]
 [5 5 2 4 7]
 [8 9 1 7 1]
 [3 2 3 0 8]]


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [18]:
with open('C:/Users/Utente/Desktop/test/data.txt', 'r') as f:
    with open('C:/Users/Utente/Desktop/test/data.csv', 'w') as f1:
        for line in f:
            index = 0
            for c in line.split():
                if(index == 0):
                    f1.write(c)
                else:
                    f1.write(','+c)
                index += 1
            f1.write('\n')

4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


In [27]:
file_name = 'C:/Users/Utente/Downloads/mushrooms_categorized.csv'
df=pd.read_csv(file_name, skiprows=1)
print(df)


      1  5  2  4  1.1  6  1.2  0  1.3  4.1  ...  2.2  7  7.1  0.2  2.3  1.4  \
0     0  5  2  9    1  0    1  0    0    4  ...    2  7    7    0    2    1   
1     0  0  2  8    1  3    1  0    0    5  ...    2  7    7    0    2    1   
2     1  5  3  8    1  6    1  0    1    5  ...    2  7    7    0    2    1   
3     0  5  2  3    0  5    1  1    0    4  ...    2  7    7    0    2    1   
4     0  5  3  9    1  0    1  0    0    5  ...    2  7    7    0    2    1   
...  .. .. .. ..  ... ..  ... ..  ...  ...  ...  ... ..  ...  ...  ...  ...   
8118  0  3  2  4    0  5    0  0    0   11  ...    2  5    5    0    1    1   
8119  0  5  2  4    0  5    0  0    0   11  ...    2  5    5    0    0    1   
8120  0  2  2  4    0  5    0  0    0    5  ...    2  5    5    0    1    1   
8121  1  3  3  4    0  8    1  0    1    0  ...    1  7    7    0    2    1   
8122  0  5  2  4    0  5    0  0    0   11  ...    2  5    5    0    1    1   

      4.2  2.4  3.1  5.1  
0       4    3    2    1

7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.